name: iSkin
main: com.iCode.iskin.iSkin
version: 1.2
authors: [Hoddie54, thehutch]
description: Changes player's skin using SpoutCraft
softdepend: [Spout]
commands:
    iskin:        
        description: Main iSkin command
        usage: /<command>       